[versions]
jreleaser = "1.18.0"
asm = "9.8"
snakeyaml = "2.4"
spigot = "1.12.2-R0.1-SNAPSHOT"
placeholderapi = "2.11.6"
lombok = "1.18.38"
log4j = "2.24.3"
slf4j = "2.0.17"
hikariCP = "4.0.3"
mybatis = "3.5.19"
jedis = "6.0.0"
byte-buddy = "1.17.5"
h2 = "2.3.232"
maven-resolver-supplier = "1.9.22"

[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }

[libraries]
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP" }
mybatis = { group = "org.mybatis", name = "mybatis", version.ref = "mybatis" }
jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }
byte-buddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byte-buddy" }
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
maven-resolver-supplier = { group = "org.apache.maven.resolver", name = "maven-resolver-supplier", version.ref = "maven-resolver-supplier" }
